-keep class io.github.supermonster003.autojs6.plugin.rapidocr.ppocrv6.OcrService { *; }
-keep class io.github.supermonster003.autojs6.plugin.rapidocr.ppocrv6.OcrService$* { *; }
-keep class io.github.supermonster003.autojs6.plugin.rapidocr.ppocrv6.WakeActivity { *; }
