-keep class io.github.supermonster003.autojs6.plugin.rapidocr.ppocrv3.OcrService { *; }
-keep class io.github.supermonster003.autojs6.plugin.rapidocr.ppocrv3.OcrService$* { *; }
-keep class io.github.supermonster003.autojs6.plugin.rapidocr.ppocrv3.WakeActivity { *; }
